apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: my-deployment
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world 
    spec:
      containers:
      - name: hello
        image: 
        ports:
        - containerPort: 80
